New development project 2
monicah79/Personal-portfolio pull request #5
Opened 2022-09-30 11:05 UTC by monicah79

I did button styling
changed colors

2022-09-30 11:55 UTC, franclobo requested changes
Hi @monicah79, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Please 🙏🏽 do not merge or delete a  branch that hasn't been approved before. You have deleted this [branch](https://github.com/monicah79/Personal-portfolio/pull/2) 👇🏽 
![image](https://user-images.githubusercontent.com/58642949/193259746-ca367244-4a35-47dc-be2b-30bfcc76a9fc.png)

- [ ] Kindly use two lines for "Multi-Post Stories" and correct the color of "Back End dev 2015" in all the cards, it is grey and there are circles between the words, to look like the Figma template 👇🏽 

| **Figma template** | **Your design** |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/193260967-a8dfa10c-1e83-4921-b40c-28fea14c78d3.png) | ![image](https://user-images.githubusercontent.com/58642949/193260839-c6c0b955-1a86-461c-8db8-5640646c781b.png) |

- [ ] As the last code reviewer said 👉🏽 You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Please make sure that your work section uses the font and colors (background and font) defined for the template and also **section has the margins (top, bottom, left, right) defined in the design.**

- **Your design**

![image](https://user-images.githubusercontent.com/58642949/193263603-97ff0c52-d930-4256-96f2-be4073710d61.png)

![image](https://user-images.githubusercontent.com/58642949/193263932-6d778156-78cc-4038-81d6-747d0f6ebc7e.png)

- **Figma template**

![image](https://user-images.githubusercontent.com/58642949/193264022-d307aad4-25a3-4bf0-9470-a51beff37029.png)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 11:55 UTC, franclobo commented on index.html
> +        LET'S CONNECT</h2>
- [ ] Please 🙏🏽 Correct the `font-size` of "About my self" and the color of "LET'S CONNECT" to look like the Figmr template.

| **Figma template** | **Your design**|
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/193261806-3fb3bfa3-06b6-4e94-ace1-68c00c5a7a5b.png) | ![image](https://user-images.githubusercontent.com/58642949/193261930-ea0f5b02-89dc-4a5e-baf4-672d87262b1a.png)
 |

2022-09-30 11:55 UTC, franclobo commented on index.html
> +            <li class="language-heading"> Language
- [ ] Please 🙏🏽 correct the word "Language", it is plural "Languages" to be similar to the Figma template.

2022-09-30 11:55 UTC, franclobo commented on index.html
> +        <li class="language-heading">Framework
- [ ] Please 🙏🏽 correct the word "Framework", it is plural "Frameworks" to be similar to the Figma template.

2022-09-30 11:55 UTC, franclobo commented on style.css
> +}
- [ ] Kindly correct the margin of this section to look similar to the Figma template. 👇🏽 

| **Figma template** | **Your template** |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/193262919-80fb2165-a58d-497b-8de0-b7e50a30368a.png) | ![image](https://user-images.githubusercontent.com/58642949/193262846-93333c97-ba64-4fd4-b634-f677884193bf.png) |

2022-10-01 10:50 UTC, monicah79 commented
done the changes

2022-10-01 10:56 UTC, closed without merging